### ISSUE TITLE
License of the Repo

### ISSUE THREAD

**Issue by hcwang95** [ilegendforever/BDNet#5]
Hi there, thanks for sharing the code!

I am trying to use the code and cite it in my paper but I need to get clearance of the License requirement.

If you have time, would you mind updating the License information of your code base?

Thanks a lot!

**Comment by zhetongliang** [comment]
Thank you for your interest.
You can freely use the code.

Best,
Zhetong



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月11日 06:41 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [zhetongliang/BDNet] License of the Repo (Issue #5) |

Hi there, thanks for sharing the code!

I am trying to use the code and cite it in my paper but I need to get clearance of the License requirement.

If you have time, would you mind updating the License information of your code base?

Thanks a lot!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
